### ISSUE TITLE
Error while updating prop transform   of a view managed by:RCTView

### ISSUE THREAD

**Issue by russelRajitha** [n4kz/react-native-indicators#25]
Error while updating prop transform of a view managed by:RCTView
distance must be finite & positive, given=NaN

java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.uimanager.ViewManagersPropertyCache$PropSetter.updateViewProp(ViewManagersPropertyCache.java:80)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater$FallbackViewManagerSetter.setProperty(ViewManagerPropertyUpdater.java:129)
        at com.facebook.react.uimanager.ViewManagerPropertyUpdater.updateProps(ViewManagerPropertyUpdater.java:48)
        at com.facebook.react.uimanager.ViewManager.updateProperties(ViewManager.java:32)
        at com.facebook.react.uimanager.NativeViewHierarchyManager.updateProperties(NativeViewHierarchyManager.java:122)
        at com.facebook.react.uimanager.UIImplementation.synchronouslyUpdateViewOnUIThread(UIImplementation.java:332)
        at com.facebook.react.animated.PropsAnimatedNode.updateView(PropsAnimatedNode.java:99)
        at com.facebook.react.animated.NativeAnimatedNodesManager.updateNodes(NativeAnimatedNodesManager.java:543)
        at com.facebook.react.animated.NativeAnimatedNodesManager.runUpdates(NativeAnimatedNodesManager.java:452)
        at com.facebook.react.animated.NativeAnimatedModule$1.doFrameGuarded(NativeAnimatedModule.java:100)
        at com.facebook.react.uimanager.GuardedFrameCallback.doFrame(GuardedFrameCallback.java:29)
        at com.facebook.react.modules.core.ReactChoreographer$ReactChoreographerDispatcher.doFrame(ReactChoreographer.java:134)
        at com.facebook.react.modules.core.ChoreographerCompat$FrameCallback$1.doFrame(ChoreographerCompat.java:105)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:964)
        at android.view.Choreographer.doCallbacks(Choreographer.java:790)
        at android.view.Choreographer.doFrame(Choreographer.java:721)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:951)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7319)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:934)
     Caused by: java.lang.IllegalArgumentException: distance must be finite & positive, given=NaN

Android: 9,
Mac os
![Screenshot_1562658217 ](https://user-images.githubusercontent.com/26809124/60868813-660ebe80-a24b-11e9-939a-431ab49fc40a.png )

**Comment by azhararmar** [comment]
Same Issue

**Comment by shenl923** [comment]
The library has not been updated for a long time so don't use !,  After version 0.59 and there are a lot of incompatibilities

**Comment by n4kz** [comment]
Thanks for issue and sorry for delayed reply. Could you provide more details or code sample? I've tested example project on Android 9 and 10 and could not reproduce this crash.

**Comment by azhararmar** [comment]
The RN version I checked was with 0.57 and 0.58, however with the new version of 0.61 this seems issue does not seem to exist.

**Comment by rodrigomf24** [comment]
was anyone able to fix this? I am using RN 0.56.1 and 0.13.0 from this library
